baseurl = "https://zellyn.com/"
languageCode = "en-us"
title = "zellyn.com"
author = "Zellyn Hunter"
disqusShortname = "zellyn"
publishDir = "docs"

[Params]
  logo = "img/zellyn.jpg"

[Author]
  name = "Zellyn Hunter"
  email = "zellyn@zellyn.com"
  facebook = "zellyn"
  github = "zellyn"
  twitter = "zellyn"
  linkedin = "in/zellyn"
  stackoverflow = "23582/zellyn"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Project TODOs"
    url = "/page/projects/todo/"
    weight = 2
